export const LOGIN_WITH_EMPLOYEE = 'LOGIN_WITH_EMPLOYEE';
export const LOGIN_WITH_EMPLOYEE_SUCCESS = 'LOGIN_WITH_EMPLOYEE_SUCCESS';
export const LOGIN_WITH_EMPLOYEE_FAILURE = 'LOGIN_WITH_EMPLOYEE_FAILURE';


export const REGISTER_WITH_EMPLOYEE = 'REGISTER_WITH_EMPLOYEE';
export const REGISTER_WITH_EMPLOYEE_SUCCESS = 'REGISTER_WITH_EMPLOYEE_SUCCESS';
export const REGISTER_WITH_EMPLOYEE_FAILURE = 'REGISTER_WITH_EMPLOYEE_FAILURE';


export const SUPER_WITH_EMPLOYEE = 'SUPER_WITH_EMPLOYEE';
export const SUPER_WITH_EMPLOYEE_SUCCESS = 'SUPER_WITH_EMPLOYEE_SUCCESS';
export const SUPER_WITH_EMPLOYEE_FAILURE = 'SUPER_WITH_EMPLOYEE_FAILURE';

